### PR TITLE
[JENKINS-64107] Convert SSHD module to a plugin

### PR DESCRIPTION
**Pull request by kuisathaverat**
[JENKINS-55582](https://issues.jenkins-ci.org/browse/JENKINS-55582) Convert modules to plugins
[JENKINS-64107](https://issues.jenkins-ci.org/browse/JENKINS-64107) Convert SSHD module to a plugin
[JEP](https://github.com/jenkinsci/jep/pull/326) Convert modules to plugins

* This PR change to use the  sshd-plugin
* Bump the Core to the 2.282

### CODE REVIEW

**Comment by kuisathaverat** [comment]
waiting for the core 2.282 to be released

**Comment by kuisathaverat** [comment]
@jglick @Vlatombe It fails to generate the injected test, it sounds like something with the class loader but I am not sure (maybe https://issues.jenkins.io/browse/JENKINS-60295).

```
[2021-03-13T14:20:27.162Z] [INFO] Running BasicUnitTests
[2021-03-13T14:20:27.543Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.314 s - in BasicUnitTests
[2021-03-13T14:20:27.543Z] [INFO] Running InjectedTest
[2021-03-13T14:20:47.469Z] [ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.479 s <<< FAILURE! - in InjectedTest
[2021-03-13T14:20:47.470Z] [ERROR] org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive  Time elapsed: 0.013 s  <<< ERROR!
[2021-03-13T14:20:47.470Z] java.lang.Error: Plugin workflow-api failed to start
[2021-03-13T14:20:47.470Z] 	at org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive(PluginAutomaticTestBuilder.java:99)
[2021-03-13T14:20:47.470Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-03-13T14:20:47.470Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
...
[2021-03-13T14:20:47.470Z] Caused by: java.io.IOException: Failed to load: Pipeline: API (2.41)
[2021-03-13T14:20:47.470Z]  - Update required: SCM API Plugin (2.6.3) to be updated to 2.6.4 or higher
[2021-03-13T14:20:47.470Z] 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:963)
[2021-03-13T14:20:47.470Z] 	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
[2021-03-13T14:20:47.470Z] 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
[2021-03-13T14:20:47.470Z] 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
[2021-03-13T14:20:47.470Z] 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1130)
[2021-03-13T14:20:47.470Z] 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
[2021-03-13T14:20:47.470Z] 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
[2021-03-13T14:20:47.470Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2021-03-13T14:20:47.470Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-03-13T14:20:47.470Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-03-13T14:20:47.470Z] 	... 1 more
```

**Comment by jglick** [comment]
The POM just needs a lot of work here. See #26.

**Comment by kuisathaverat** [comment]
a year without progress I close it

**Comment by jglick** [comment]
Better to keep it open so it is visible in the list of things that need to be cleaned up. @justnoxx cut a release just a month ago.

**Comment by jtnord** [comment]
obsoleted by #311

**Pull request closed without merging**
