### PR TITLE
Rebranding: renaming triggerSource and associationType enums

### PR DESCRIPTION
**Pull request by horodchukanton**
This change is required for SDA plugin to show up to date values.

- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by dwnusbaum — APPROVED** [review]
Are you ok with old serialized instances of `CloudBeesCDPBABuildDetails` losing their `triggerSource` or `buildAssociationType` fields after upgrading the plugin to a version that includes this PR if the previous values were `FLOW` or `TRIGGERED_BY_FLOW`? If so, then this PR looks fine to me.

If not, you might want to leave the old enum values around for backwards compatibility and add a `readResolve` method to convert the old values to the new values in `CloudBeesCDPBABuildDetails` and any other places where they were being serialized.

**Comment by horodchukanton** [comment]
@dwnusbaum Yes, your suggestion is correct. I tried to avoid additional mess in code, but simple renaming will force users to "Discard unreadable data". We cannot add exported String getter, as there's already one with a type.

**Review by dwnusbaum — APPROVED** [review]

**Review by justnoxx — APPROVED** [review]

**Comment by dwnusbaum** [comment]
Looking at this again, I think a few parts of a0a75f3 should have been kept, since right now we are not actually using the new enums anywhere except for in the `readResolve` method. Specifically, I think these lines https://github.com/jenkinsci/electricflow-plugin/blob/3d05494fa1baef634f4dfe3f5fb5894798a580a7/src/main/java/org/jenkinsci/plugins/electricflow/event/ElectricFlowBuildWatcher.java#L108-L109 as well as these https://github.com/jenkinsci/electricflow-plugin/blob/3d05494fa1baef634f4dfe3f5fb5894798a580a7/src/main/java/org/jenkinsci/plugins/electricflow/event/ElectricFlowBuildWatcher.java#L209-L210

should be updated to use the new enum values, right?

Also, I think the new enum values need to be added to the switch statements in [`CIBuildDetails.getBuildTriggerSource`](https://github.com/jenkinsci/electricflow-plugin/blob/7092fa7e6ed69d1ed6127d06fdce8823457ac777/src/main/java/org/jenkinsci/plugins/electricflow/models/CIBuildDetail.java#L117) and [`CIBuildDetails.getAssociationType`](https://github.com/jenkinsci/electricflow-plugin/blob/7092fa7e6ed69d1ed6127d06fdce8823457ac777/src/main/java/org/jenkinsci/plugins/electricflow/models/CIBuildDetail.java#L133).

Is it ok if I file a PR to make those changes, or were they left out intentionally?

**Comment by horodchukanton** [comment]
@dwnusbaum No, it was not intentional, so it's okay to change other lines.

**Pull request merged**
