### PR TITLE
Bump parent pom from 4.51 to 4.58

### PR DESCRIPTION
**Pull request by alecharp**
Updating the parent pom so the plugin is getting the new Jenkins Test Harness and is still validated with PCT.
The new parent pom required to bump Jenkins version requirement and to fix a bit of code.

Closes #355.
Closes #343.

### Testing done

Ran `mvn verify` without problem.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by alecharp** [comment]
Please @jsmith-cb, consider this pull request over #363 and #362. 
Those requires more testing / review when this one is the bare minimum of what we need for PCT to pass.

**Comment by alecharp** [comment]
The build configuration (`Jenkinsfile`) is failing when the build on Java 11 has no problem locally.

**Comment by alecharp** [comment]
When looking at the build log, the java version used is `1.8` when we are on the `linux-11` node. This is not normal.

**Comment by jsmith-cb** [comment]
@alecharp,
In your opinion, do these changes require a change log entry?

**Comment by alecharp** [comment]
> @alecharp, In your opinion, do these changes require a change log entry?

my opinion is that we always needs a changelog entry. But this is mostly "chore" work, nothing that a enduser would / should notice.

**Review by basil — APPROVED** [review]
Thanks!

**Pull request merged**
